export const STRINGS = {
  appName: 'PadelTop',
  welcomeTitle: 'Bienvenido a PadelTop',
  welcomeSubtitle: 'Sigue el pádel profesional en tiempo real',
  login: 'Iniciar sesión',
  register: 'Registrarse',
  logout: 'Cerrar sesión',
  matches: 'Partidos',
  tournaments: 'Torneos',
  rankings: 'Rankings',
  more: 'Más',
  home: 'Inicio',
  live: 'En directo',
  today: 'Hoy',
  results: 'Resultados',
  favorites: 'Favoritos',
  settings: 'Ajustes',
  premium: 'Premium',
  notifications: 'Notificaciones',
  male: 'Masculino',
  female: 'Femenino',
  darkMode: 'Modo oscuro',
  lightMode: 'Modo claro',
  systemMode: 'Predeterminado del sistema',
};
